framework:
    serializer:
        enable_annotations: true
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        cookie_httponly: false
        enabled: true
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        gc_maxlifetime: 2592000
        cookie_lifetime: 2592000

    #esi: true
    #fragments: true
    php_errors:
        log: true
